colors:
  "#orange": UI interaction
  "#red": External manual interaction
  "#black": Internal System interaction
  "#blue": Cross-system REST Call interaction via API Gateway
  "#purple": Direct Cross-system interaction via REST Call
  "#green": Cross-system Streaming (Kafka) message interaction
  "#brown": Reference to external process